### ISSUE TITLE
JUnit report annotation issue despite proper reporting

### ISSUE THREAD

**Issue by opatry** [opatry/todoist-kt#3]
**Describe the bug**
When running CI jobs, the test reports are published thanks to [Mike Penz's action-junit-report Github action](https://github.com/mikepenz/action-junit-report).

Each time it's executed, the following annotation is reported:
> [!CAUTION]
> ❌ Failed to create checks using the provided token. (HttpError: Resource not accessible by integration)

> [!WARNING]
> ⚠️ This usually indicates insufficient permissions. More details: https://github.com/mikepenz/action-junit-report/issues/23

**To Reproduce**
1. Any PR or `main` build running tests

**Expected behavior**
No annotation "❌ Failed to create checks using the provided token. (HttpError: Resource not accessible by integration)" is expected

**Screenshots**
![action-junit-report](https://github.com/opatry/todoist-kt/assets/362710/62cd7c86-ae6f-459c-baeb-483ae76ccbb3)

**Comment by opatry** [comment]
Need to add
```yaml
permissions:
    contents: read
    checks: write
    id-token: write
```
Right after `runs-on`

**Comment by LLotme** [comment]
im really sorry and thank you for all
